### ISSUE TITLE
Cannot Paste connection string. 

### ISSUE THREAD

**Issue by hbrock** [peschkaj/soddi#14]
I can copy and cute strings for the textboxes controls but cannot paste anything into them.

Is there any plans to fix this? If not I might make a fork and fixed the issue.

**Comment by peschkaj** [comment]
I'm able to copy and paste into the Source, Target, and Provider textboxes using version 1.2 from the [releases](https://github.com/peschkaj/soddi/releases) page.

Can you try with the current version from that page?

Which version of the .NET Framework are you using? 

You can figure out the available versions through `dir C:\Windows\Microsoft.NET\Framework`. 

You should have v3.5 and you can check the build number of that version with `C:\Windows\Microsoft.NET\Framework\v3.5\csc.exe -version`.

Any additional information will help figure out the problem.

**Comment by hbrock** [comment]
Thanks. I have version 1.0

**Comment by peschkaj** [comment]
I'd suggest updating to the current version. If the issue still occurs on the current version, then comment on this issue again and we'll re-open it and look into it.
